POST http://127.0.0.1:8001/tpdf/create_directory/409f05934Rtyh
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test_file.pdf"
Content-Type: application/pdf

%PDF-1.4
%...
--boundary--
